export const Auth = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  AUTHENTICATION_REQUEST: "AUTHENTICATION_REQUEST",
};
export const Device = {
  GET_DEVICES_DATA_REQUEST: "GET_DEVICES_DATA_REQUEST",
  GET_DEVICES_DATA_SUCCESS: "GET_DEVICES_DATA_SUCCESS",
  GET_DEVICES_DATA_FAILED: "GET_DEVICES_DATA_FAILED",
};
